/** @type {import('@commitlint/types').UserConfig} */
module.exports = {
  extends: ["@commitlint/config-conventional"],
  plugins: [
    {
      rules: {
        "no-ai-attribution": ({ raw }) => {
          const text = String(raw || "")
          const has = /co-authored-by:|generated by (claude|chatgpt|copilot|ai)|🤖/i.test(text)
          return [
            !has,
            "commit must not attribute work to AI (no Co-authored-by, no AI references)",
          ]
        },
        "no-pm-id-in-subject": ({ subject }) => {
          const s = String(subject || "")
          const has = /\b[A-Z]{2,}-\d+\b/.test(s)
          return [!has, "commit subject must not contain PM-style IDs (e.g. WORK-11)"]
        },
      },
    },
  ],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "refactor",
        "docs",
        "chore",
        "test",
        "perf",
        "style",
        "build",
        "ci",
        "revert",
      ],
    ],
    "subject-case": [2, "always", "lower-case"],
    "body-leading-blank": [0],
    "footer-leading-blank": [0],
    "no-ai-attribution": [2, "always"],
    "no-pm-id-in-subject": [2, "always"],
  },
}
